Dcp 600: Return null when submission is empty
ebi-ait/ingest-core pull request #114
Opened 2022-02-09 12:52 UTC by aaclan-ebi

2022-02-10 13:17 UTC, jacobwindsor approved these changes

2022-02-11 00:18 UTC, amnonkhen requested changes

2022-02-11 00:18 UTC, amnonkhen commented on src/main/java/org/humancellatlas/ingest/submission/SubmissionEnvelopeService.java
> +import javax.swing.text.html.Option;
Is this a correct import?

2022-02-11 00:18 UTC, amnonkhen commented on src/main/java/org/humancellatlas/ingest/submission/web/SubmissionController.java
> +        return ResponseEntity.ok(lastUpdateDate.isPresent() ? lastUpdateDate.get().toString() : null);
Have you considered
```suggestion
        return ResponseEntity.ok(lastUpdateDate.map(Instant::toString).orElse(null));
```

2022-02-11 00:18 UTC, amnonkhen commented on src/main/java/org/humancellatlas/ingest/submission/web/SubmissionController.java
> +        return ResponseEntity.ok(lastUpdateDate.isPresent() ? lastUpdateDate.get().toString() : null);
What does the null case mean here?
Would it be correct to have an `ok(null)` return value?

2022-02-11 00:18 UTC, amnonkhen commented on src/test/java/org/humancellatlas/ingest/submission/SubmissionEnvelopeServiceTest.java
> +        assertThat(lastUpdateDate.get().toString()).isEqualTo(now.toString());
AssertJ handles Optionals elegantly.
See https://www.baeldung.com/assertJ-java-8-features
```suggestion
        assertThat(lastUpdateDate)
            .isPresent()
            .hasValue(now.toString());
```

2022-02-11 00:19 UTC, amnonkhen approved these changes

2022-02-11 09:48 UTC, merged