911 project grouping filtering by biological network
ebi-ait/ingest-core pull request #148
Opened 2023-02-09 15:45 UTC by Mil-m

2023-02-15 10:39 UTC, amnonkhen commented
Please pay attention to PR and branch naming conventions.
They need to start with `dcp-`, for example dcp-911. This is how the automatic linking from branches, commits & PRs to issues and tickets works.

2023-02-15 10:40 UTC, amnonkhen requested changes

2023-02-15 10:40 UTC, amnonkhen commented on src/integration/java/org/humancellatlas/ingest/project/ProjectFilterTest.java
> +                "",
Don't use empty strings as parameters. Use some generic network name instead.

2023-02-15 14:35 UTC, Mil-m commented on src/integration/java/org/humancellatlas/ingest/project/ProjectFilterTest.java
> +                "",
like - 'a network'?

2023-02-15 14:37 UTC, Mil-m commented
> Please pay attention to PR and branch naming conventions. They need to start with `dcp-`, for example [dcp-911](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/911). This is how the automatic linking from branches, commits & PRs to issues and tickets works.

as I see we have 'dcp-911' both in the name of this branch 911-project-grouping-filtering-by-biological-network and in the commit names also

2023-03-02 00:40 UTC, amnonkhen commented
@Mil-m have you noticed the tests are failing on gitlab?
![image](https://user-images.githubusercontent.com/927145/222300081-5e72622f-fa6e-409f-bde2-f552425740c6.png)
Have you ran the tests locally?

2023-03-03 00:49 UTC, amnonkhen approved these changes

2023-03-03 00:50 UTC, merged