issue#160: added submit action `EXPORT_METADATA` to cater to exporting only metadata
ebi-ait/ingest-core pull request #60
Opened 2021-03-09 07:44 UTC by yusra-haider

Fixes [#160](https://app.zenhub.com/workspaces/dcp-ingest-product-development-5f71ca62a3cb47326bdc1b5c/issues/ebi-ait/dcp-ingest-central/160)

Related PRs:
In UI: https://github.com/ebi-ait/ingest-ui/pull/82
In exporter: https://github.com/ebi-ait/ingest-exporter/pull/18

2021-03-09 17:22 UTC, aaclan-ebi approved these changes

2021-03-09 21:31 UTC, amnonkhen requested changes

2021-03-09 21:31 UTC, amnonkhen commented on src/main/java/org/humancellatlas/ingest/submission/SubmissionEnvelopeService.java
> +        if (submitActions.contains(SubmitAction.ARCHIVE) || submitActions.contains(SubmitAction.EXPORT) || submitActions.contains(SubmitAction.EXPORT_METADATA)) {
Consider extracting a method from the compound predicate.

2021-03-09 21:31 UTC, amnonkhen commented on src/main/java/org/humancellatlas/ingest/submission/SubmissionEnvelopeService.java
> +        } else if (envelope.getSubmitActions().contains(SubmitAction.EXPORT) || envelope.getSubmitActions().contains(SubmitAction.EXPORT_METADATA)) {
Consider extracting a method.

2021-03-19 13:29 UTC, amnonkhen requested changes

2021-03-19 13:29 UTC, amnonkhen commented on src/main/java/org/humancellatlas/ingest/submission/SubmissionEnvelopeService.java
> +//import org.humancellatlas.ingest.core.service.MetadataUpdateService;
This can be deleted.

2021-03-19 13:29 UTC, amnonkhen commented on src/main/java/org/humancellatlas/ingest/submission/SubmissionEnvelopeService.java
> +        } else if (envelope.getSubmitActions().contains(SubmitAction.EXPORT) || envelope.getSubmitActions().contains(SubmitAction.EXPORT_METADATA)) {
This can also be extracted to a function, similarly to `isSubmitAction()`

2021-03-19 14:48 UTC, amnonkhen submitted a review, later dismissed

2021-03-19 15:00 UTC, aaclan-ebi approved these changes
Thanks for doing the cleanup.

2021-03-22 12:07 UTC, yusra-haider commented
integration tests are passing

2021-03-22 12:08 UTC, aaclan-ebi approved these changes

2021-03-22 12:46 UTC, amnonkhen approved these changes

2021-03-22 12:49 UTC, merged