Serialisation and deserialisation of wrangling enum fields
ebi-ait/ingest-core pull request #70
Opened 2021-05-28 14:56 UTC by aaclan-ebi

2021-05-28 15:54 UTC, ke4 reviewed
I can't really see how is that generating a JSON.
It is just generating `"New"`, but don't we want to get `{"WranglingState": "New"}`?

Maybe we could implement this: https://www.baeldung.com/jackson-serialize-enums#2-enum-as-json-object

2021-05-28 17:58 UTC, ke4 commented
What about the `@JsonValue` annotation on a getter in the Enum class? That might be shorter and cleaner.
Like in the example here: https://www.baeldung.com/jackson-serialize-enums#2-using-jsonvalue

2021-06-01 08:54 UTC, MightyAx requested changes
Also the test fail

2021-06-01 08:54 UTC, MightyAx commented on src/test/java/org/humancellatlas/ingest/project/wranglingpriority/WranglingStateTest.java
> +@RunWith(SpringRunner.class)
This line forces the tests to use JUnit Vintage tests rather than the new JUnit Jupiter runner.
It can be removed.

2021-06-01 09:13 UTC, MightyAx approved these changes

2021-06-01 11:01 UTC, jacobwindsor approved these changes

2021-06-01 11:47 UTC, aaclan-ebi commented
Thanks for the reviews guys!

And special thanks to the great suggestion by @ke4 ! That simplified the original changes I had!

2021-06-01 11:48 UTC, merged