Added new cell count attribute to project
ebi-ait/ingest-core pull request #72
Opened 2021-06-09 11:53 UTC by aaclan-ebi

2021-06-09 13:44 UTC, amnonkhen requested changes

2021-06-09 13:44 UTC, amnonkhen commented on src/main/java/org/humancellatlas/ingest/project/web/ProjectController.java
> +                "accessionDate", "technology", "organ", "cellCount", "dataAccess", "identifyingOrganisms", "validationErrors", "isInCatalogue", "publicationsInfo");
I would format this list as one entry per line. Even sort it. It would make diffs easier to notice.

2021-06-09 13:45 UTC, ke4 approved these changes
Looks fine by me 👍 💯

2021-06-09 15:30 UTC, jacobwindsor approved these changes

2021-06-10 08:41 UTC, amnonkhen approved these changes

2021-06-10 09:31 UTC, ke4 approved these changes

2021-06-10 10:01 UTC, merged