Submission Census
ebi-ait/ingest-core pull request #97
Opened 2021-11-22 12:03 UTC by MightyAx

Work In Progress: Using `/submissionEnvelopes/{sub_id}/summary` as a reference.

Census: all object contained within a submission and their relationships to each other.
Initially just uuid's and api links but perhaps all content of objects too...
- [x] Decide on location: /submissionEnvelopes/{sub_id}/census
- [ ] Decide on document format
- [ ] populate data into format
- [ ] test speediness

2021-11-23 10:20 UTC, MightyAx commented
At this prototype stage which only populates relationship data for processes.
it takes 1 min 30 seconds for core to generate the return file of 3 thousand processes, but transfer time is negligible due to the local network..
![Screenshot 2021-11-23 at 10 14 16](https://user-images.githubusercontent.com/13031259/143006319-08a33286-e996-4c57-8f85-c2f8ece30e7d.png)

2021-11-23 11:02 UTC, MightyAx commented
Reversed the mapping direction to make most useful for spreadsheet downloader.
3 Minutes for a complete relationship map of a 3 thousand process submission.
![Screenshot 2021-11-23 at 10 58 16](https://user-images.githubusercontent.com/13031259/143012850-add9178d-81f8-4233-a40f-97178a309cfb.png)

2021-11-24 15:01 UTC, aaclan-ebi commented
Sample request and output:
```
$ curl -X GET -H "Accept: application/hal+json" -H "Content-Type: application/hal+json" http://localhost:8080/submissionEnvelopes/619738062807a377aad3a2ff/linkingMap | jq > linking-map.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1073    0  1073    0     0   1407      0 --:--:-- --:--:-- --:--:--  1438
$ cat linking-map.json
{
  "processes": {
    "6197380b2807a377aad3a30e": {
      "protocols": [
        "6197380b2807a377aad3a30a",
        "6197380b2807a377aad3a30b"
      ],
      "inputBiomaterials": [
        "6197380b2807a377aad3a304"
      ],
      "inputFiles": []
    },
    "6197380b2807a377aad3a30d": {
      "protocols": [
        "6197380b2807a377aad3a308",
        "6197380b2807a377aad3a309"
      ],
      "inputBiomaterials": [
        "6197380b2807a377aad3a303"
      ],
      "inputFiles": []
    },
    "6197380b2807a377aad3a30c": {
      "protocols": [
        "6197380b2807a377aad3a307"
      ],
      "inputBiomaterials": [
        "6197380b2807a377aad3a302"
      ],
      "inputFiles": []
    }
  },
  "protocols": {},
  "biomaterials": {
    "6197380b2807a377aad3a304": {
      "derivedByProcesses": [
        "6197380b2807a377aad3a30d"
      ],
      "inputToProcesses": [
        "6197380b2807a377aad3a30e"
      ]
    },
    "6197380b2807a377aad3a303": {
      "derivedByProcesses": [
        "6197380b2807a377aad3a30c"
      ],
      "inputToProcesses": [
        "6197380b2807a377aad3a30d"
      ]
    },
    "6197380b2807a377aad3a302": {
      "derivedByProcesses": [],
      "inputToProcesses": [
        "6197380b2807a377aad3a30c"
      ]
    }
  },
  "files": {
    "6197380b2807a377aad3a306": {
      "derivedByProcesses": [
        "6197380b2807a377aad3a30e"
      ],
      "inputToProcesses": []
    },
    "6197380b2807a377aad3a305": {
      "derivedByProcesses": [
        "6197380b2807a377aad3a30e"
      ],
      "inputToProcesses": []
    }
  }
}
```

2021-11-24 15:59 UTC, ke4 commented
> Reversed the mapping direction to make most useful for spreadsheet downloader. 3 Minutes for a complete relationship map of a 3 thousand process submission. ![Screenshot 2021-11-23 at 10 58 16](https://user-images.githubusercontent.com/13031259/143012850-add9178d-81f8-4233-a40f-97178a309cfb.png)

I can't really decide if it is slow or fast. I would rather say it is extremely slow, but I am not 100% familiar with this feature.

2021-11-24 16:02 UTC, ke4 requested changes
I can't see any unit or integration tests. Please add them. Tx

2021-11-25 12:50 UTC, jacobwindsor approved these changes

2021-11-25 15:22 UTC, ke4 approved these changes

2021-11-25 15:29 UTC, merged

2021-11-30 13:46 UTC, aaclan-ebi commented
Just wanna note here:  Deployed core in dev returns the linking map in 1min for the same submission https://api.ingest.dev.archive.data.humancellatlas.org/submissionEnvelopes/5cdb0344d96dad000858fff4

```
$ curl -X GET -H "Accept: application/hal+json" -H "Content-Type: application/hal+json" https://api.ingest.dev.archive.data.humancellatlas.org/submissionEnvelopes/5cdb0344d96dad000858fff4/linkingMap | jq > linking-map.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:  0     0    0     0    0     0      0      0 --:--:--  0:00:59 --:--:--     0

````

2021-12-06 12:03 UTC, MightyAx commented on src/main/java/org/humancellatlas/ingest/submission/web/SubmissionLinkMapController.java
> +        final Dictionary<String, UUID> protocols = new Hashtable<>();
I think this line is unused. Protocols are now returned as part of `this.processes`